services:
  - type: web
    name: weather-prediction-api
    env: python
    buildCommand: "pip install -r requirements.txt && python train_models.py --csv Kolkata.csv"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
